apiVersion: skaffold/v2beta13
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: tangyisheng2/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: 'src/**/*.ts'
            src: .
    - image: tangyisheng2/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: '**/*.js'
            src: .

    - image: tangyisheng2/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - dest: 'src/**/*.ts'
            src: .
